### ISSUE TITLE
Top menu layout breaks on windows under about 1000 pixels wide

### ISSUE THREAD

**Issue by MichaelHackett** [MyProfile/myprofile#15]
(This report is for my-profile.eu, not necessarily the source install; I have not had time to test on the latter. However, Andrei suggested posting here as the most appropriate location for the issue.)

I thought this was a browser or OS issue, but I narrowed it down to being dependent on the width of the browser window. On both Safari 5.1.5-7 and Firefox 12 on Mac (at least; that's all that I've tested), the top menu layout breaks when the window width is about 992 pixels or less. Instead of showing across the top, the items appear in a vertical column, and block access to the Login button or Post area, depending on the page.

**Comment by deiu** [comment]
Fixed in the new version/layout.
